remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile.lock
  - README.md

# Show all heading levels in the right-hand table of contents
toc:
  heading_level: 3